set nocompatible              " be improved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
  " Main group
  Plugin 'gmarik/Vundle.vim'
  Plugin 'scrooloose/nerdtree'
  Plugin 'scrooloose/syntastic'
  Plugin 'vim-scripts/tComment'
  Plugin 'kien/ctrlp.vim'
  Plugin 'Yggdroot/indentLine'
  Plugin 'bling/vim-airline'
  Plugin 'corntrace/bufexplorer'
  Plugin 'dockyard/vim-easydir'
  Plugin 'powerman/vim-plugin-ruscmd'
  Plugin 'rking/ag.vim'
  Plugin 'terryma/vim-multiple-cursors'
  Plugin 'MarcWeber/vim-addon-mw-utils.git'
  Plugin 'elzr/vim-json'
  Plugin 'garbas/vim-snipmate'
  Plugin 'gorodinskiy/vim-coloresque'
  Plugin 'majutsushi/tagbar'
  Plugin 'tomtom/tlib_vim.git'
  Plugin 'tpope/vim-surround'
  Plugin 'tpope/vim-rsi'
  Plugin 'bruno-/vim-husk'

  " Vim text objects
  Plugin 'kana/vim-textobj-user'
  Plugin 'whatyouhide/vim-textobj-erb'

  " Color schemes
  Plugin 'junegunn/seoul256.vim'
  Plugin 'davydovanton/strange'
  Plugin 'cocopon/iceberg.vim'

  " Ruby group
  Plugin 'vim-ruby/vim-ruby'
  Plugin 'tpope/vim-rails'
  Plugin 'slim-template/vim-slim'
  Plugin 'tpope/vim-endwise'
  Plugin 'thoughtbot/vim-rspec'
  Plugin 'danchoi/ri.vim'

  " tmux group
  Plugin 'christoomey/vim-tmux-navigator'
  Plugin 'jgdavey/tslime.vim'
  Plugin 'jpalardy/vim-slime'

  " js group
  Plugin 'pangloss/vim-javascript'

  " elexir group
  Plugin 'elixir-lang/vim-elixir'

  " haskell group
  Plugin 'eagletmt/neco-ghc'
  Plugin 'eagletmt/ghcmod-vim'

  " test plugin functionality

call vundle#end()            " required
filetype plugin indent on

set tags=.git/tags
set guifont=Droid\ Sans\ Mono\ 12
let g:tube_terminal = "iterm"

let g:seoul256_background = 236
colo seoul256
" colo strange
colo iceberg

syntax on

set iskeyword-=. " use dot for limiter word
set clipboard=unnamed 
set nocompatible
set ttyfast " u got a fast terminal
set ttyscroll=3
set lazyredraw " to avoid scrolling problems
set synmaxcol=200
set mouse=nv
set clipboard=exclude:.*
set hidden
set number
set ts=2
set sw=2
set autoindent
set smartindent
set expandtab
set ignorecase
set hlsearch
set splitbelow " new splits are down
set splitright " new vsplits are to the right
set smartcase
set incsearch
set laststatus=2
set visualbell
set title
set showcmd
set pastetoggle=
set iminsert=0
set linebreak
set completeopt=longest,menuone
set relativenumber
set wildmenu
set noerrorbells
set novisualbell
set t_vb=
set t_vb=
set t_ut=
set tm=500
set nobackup
set nowb
set noswapfile
set timeoutlen=500
set lazyredraw
set guioptions-=rL
set langmenu=en_US.UTF-8
set encoding=utf-8
set fileencoding=utf-8
language mes en_US.UTF-8

let g:notes_directories = ['~/Dropbox/Data/VimNotes']

let g:ruby_path = system('rvm current')

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_buffers = 0
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#syntastic#enabled = 1
let g:airline#extensions#tabline#left_sep = '|'
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_fugitive_prefix = '⎇ '
let g:airline_paste_symbol = 'ρ'
let g:airline#extensions#branch#enabled = 1
let g:airline#extensions#branch#empty_message = ''
let g:airline_theme = 'lucius'

let g:bufExplorerDefaultHelp=0
let g:bufExplorerShowRelativePath=1
let g:bufExplorerSortBy='mru'
let g:bufExplorerSplitRight=0

let g:neocomplete#enable_at_startup = 1

let g:ruby_indent_access_modifier_style = 'outdent'
let ruby_operators = 1

let g:surround_{char2nr('%')} = "%(\r)"
let g:surround_{char2nr('w')} = "%w(\r)"
let g:surround_{char2nr('#')} = "#{\r}"
let g:surround_{char2nr('|')} = "|\r|"

let g:syntastic_enable_signs = 1
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'

let g:vimrubocop_config = '~/.rubocop.yml'

" vim-slime
let g:slime_target = "tmux"

nmap <space> <leader>
nmap <leader>n :noh<CR>

nmap <F2>   :NERDTreeToggle<cr>
nmap <F3>   :TagbarToggle<CR>

nnoremap j gj
nnoremap k gk
vnoremap j gj
vnoremap k gk
nnoremap gj j
nnoremap gk k
vnoremap gj j
vnoremap gk k

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" experimental mappings------------
nnoremap <tab> >>
nnoremap <s-tab> <<
vnoremap <tab> >
vnoremap <s-tab> <

nnoremap th  :tabfirst<CR>
nnoremap tj  :tabprev<CR>
nnoremap tk  :tabnext<CR>
nnoremap tl  :tablast<CR>
nnoremap td  :tabclose<CR>
nnoremap tn  :tabnew<CR>

nmap <leader>o o<ESC>
nmap <leader>O O<ESC>j

nmap <leader>< <C-w>10<
nmap <leader>> <C-w>10>
nmap <leader>+ <C-w>10+
nmap <leader>- <C-w>10-

nmap <leader>p :CtrlPBufTag<CR>
nmap <leader>hh :%s/:\([^ ]*\)\(\s*\)=>/\1:/g<CR>
nmap <leader>;  :%s:::g<Left><Left><Left>
nmap <leader>;; :%s:::g<Left><Left>

cabbrev CSScomb :!csscomb %:p<CR>
cnoreabbrev <expr> W ((getcmdtype() is# ':' && getcmdline() is# 'W')?('w'):('W'))

"" Open current line on GitHub
" noremap ,o :!echo `git url`/blob/`git rev-parse --abbrev-ref HEAD`/%\#L<C-R>=line('.')<CR> \| xargs open<CR><CR>


" Use The Silver Searcher https://github.com/ggreer/the_silver_searcher
if executable('ag')
  " Use Ag over Grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " ag is fast enough that CtrlP doesn't need to cache
  let g:ctrlp_use_caching = 0
else
  " Fall back to using git ls-files if Ag is not available
  let g:ctrlp_custom_ignore = '\.git$\|\.hg$\|\.svn$'
  let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . --cached --exclude-standard --others']
endif
" bind K to grep word under cursor
nnoremap <leader>f :grep! "\b<C-R><C-W>\b" --ignore-dir log<CR>:cw<CR>

function! ClearRegisters()
  let regs='abcdefghijklmnopqrstuvwxyz0123456789'
  let i=0
  while (i<strlen(regs))
    exec 'let @'.regs[i].'=""'
    let i=i+1
  endwhile
endfunction
command! ClearRegisters call ClearRegisters()

" Strip trailing whitespace (,ss)
function! StripWhitespace()
  let save_cursor = getpos(".")
  let old_query = getreg('/')
  :%s/\s\+$//e
  call setpos('.', save_cursor)
  call setreg('/', old_query)
endfunction
noremap <leader>ss :call StripWhitespace()<CR>

" Automatic commands
if has("autocmd")
  " Enable file type detection
  filetype on
  " Treat .json files as .js
  autocmd BufNewFile,BufRead *.json setfiletype json syntax=javascript
endif

autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd FileType css        set omnifunc=csscomplete#CompleteCSS
autocmd Filetype gitcommit  setlocal spell textwidth=72

if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"
endif

if executable('zsh')
  set shell=zsh
endif

autocmd BufWritePost * set iskeyword-=.
autocmd BufWritePost * set clipboard=unnamed
set iskeyword-=. " use dot for limiter word
set clipboard=unnamed 
