export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell" # default theme
ZSH_THEME="excess"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Uncomment this to disable bi-weekly auto-update checks
DISABLE_AUTO_UPDATE="false"

# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=7

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment following line if you want to  shown in the command execution time stamp
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
# HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(virtualenv git vagrant web-search bundler gem brew ruby heroku tmux rvm bower)

source $ZSH/oh-my-zsh.sh

# User configuration

# scripts
# git delete local and remote merged branchs
gdmbs() {
  git branch --merged | ag '^[^*].+' | awk '{print "git branch -d "$1}' | sh && git fetch -p
}

share_file() {
  file=$1
  curl -F "file=@$file" http://curl.io/send/jnbvugmk
}

share_file_with_protected() {
  file=$1
  gpg -c "$file" && curl -F "file=@$file" http://curl.io/send/aghrldqv
}

magic_shell() {
  j=0;a=1;x=1;y=1;xd=1;yd=1;while true;do for i in {1..2000} ; do if [[ $x == $LINES || $x == 0 ]]; then xd=$(( $xd *-1 )) ; fi ; if [[ $y == $COLUMNS || $y == 0 ]]; then yd=$(( $yd * -1 )) ; fi ; x=$(( $x + $xd )); y=$(( $y + $yd )); printf "\33[%s;%sH\33[48;5;%sm . \33[0m" $x $y $(( $a % 8 + 16 + $j % 223 )) ;a=$(( $a + 1 )) ; done ; x=$(( x%$COLUMNS + 1 )) ; j=$(( $j + 8 )) ;done
}

# User commands
# export MANPATH="/usr/local/man:$MANPATH"
export PATH="/opt/local/bin:/opt/local/sbin:/Users/anton/.rvm/gems/ruby-2.0.0-p247/bin:/Users/anton/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/anton/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/anton/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/git/bin"

# Preferred editor for local and remote sessions
export EDITOR='vim'

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# ALIAS:
# System:
alias 'vbox-restart=sudo /Library/StartupItems/VirtualBox/VirtualBox restart'

# Git alias
alias gcl='git clone'
alias grb='git rebase'

# programs
alias 'airport=/System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Resources/airport -I'
alias 'ctags=/usr/local/bin/ctags'
alias 'git=/usr/local/bin/git'
alias 'octave=exec "/Applications/Octave.app/Contents/Resources/bin/octave"'
alias 'tmux=TERM=screen-256color-bce tmux'
alias 'tmuxinator=TERM=screen-256color-bce tmuxinator'
alias 'vim=/usr/local/bin/vim'
alias 'zsh=/usr/local/bin/zsh'
alias 'codespell=/Users/anton/bin/codespell/codespell.py'
